name: deploy-aws-sam-serverless

on:
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STACK_NAME: ${{ vars.STACK_NAME }}
  STACK_BUCKET: ${{ vars.STACK_BUCKET }}
  REGION: ${{ vars.REGION }}
  FILES_BUCKET: ${{ vars.FILES_BUCKET }}
  BILLING_INVOICE_GENERATION_URL: ${{ vars.BILLING_INVOICE_GENERATION_URL }}

# on:
#   push:
#     branches:
#       - master
#       - testing

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Setup aws sam
        uses: aws-actions/setup-sam@v1
      
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      
      - name: AWS SAM build
        run: sam build --use-container

      - name: AWS SAM deploy
        run: |
          sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name $STACK_NAME \
          --s3-prefix $STACK_NAME \
          --s3-bucket $STACK_BUCKET \
          --region $REGION \
          --capabilities "CAPABILITY_IAM" \
          --parameter-overrides "S3Bucket=$FILES_BUCKET,BillingInvoiceGenerationUrl=$BILLING_INVOICE_GENERATION_URL"
