name: deploy-aws-sam-serverless

# ENVIRONMENT VARS:
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# STACK_NAME
# BUCKET
# REGION

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Setup aws sam
        uses: aws-actions/setup-sam@v1
      
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ''

      - name: Install npm dependencies
        run: npm ci
      
      - name: AWS SAM build
        run: sam build --use-container

      - name: AWS SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ secrets.STACK_NAME }} --s3_prefix ${{ secrets.STACK_NAME }} --s3-bucket ${{ secrets.BUCKET }} --region ${{ secrets.REGION }} --capabilities "CAPABILITY_IAM"